AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  Test:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: dino.handler
      Runtime: provided
      CodeUri: ./src
      Layers:
        - <layer ARN Here>
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /dino
            Method: GET

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref MyApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
